### ISSUE TITLE
show the uploaded image

### ISSUE THREAD

**Issue by shibam-naskar** [shibam-naskar/IMAGE_COMPRESOR#1]
show the uploaded image on the same page in replacement of the drop area.

**Comment by thisiskushal31** [comment]
Can  you assign it to me?

**Comment by PRINCE-PRASAD** [comment]
i also wan't to contribute in this issue

**Comment by ATUL6026** [comment]
I want to work on this issue under JWOC

**Comment by firtysh** [comment]
I want to work on this issue under JWOC.

**Comment by raxvab** [comment]
I want to work on this issue under JWOC it's gonna be one of the first opportunities for me to start with open source can i get this issue assigned.

**Comment by codervivek5** [comment]
I want to work on this issue under JWOC
