### ISSUE TITLE
Design a better UI for this Webpage

### ISSUE THREAD

**Issue by ronitblenz** [shibam-naskar/IMAGE_COMPRESOR#17]
Hi, Can I design a better UI for this page.
If so, plz assign me and tag it as medium issue

Thanks

**Comment by SantanuShaw** [comment]
I want to contribute under jwoc

**Comment by ronitblenz** [comment]
I have made a PR @shibam-naskar Plz check and merge my PR

**Comment by ronitblenz** [comment]
Plz check and merge my PR....Its been long since I made the contrubution
