### ISSUE TITLE
Make a Nav Bar.

### ISSUE THREAD

**Issue by shibam-naskar** [shibam-naskar/IMAGE_COMPRESOR#2]
Add a nav bar on the top .

theme will be the same as body .

**Comment by Sanghu01** [comment]
Hey, This is Sangh Priya Gautam .I am intrested in contributing to this project but how can i work in this project .

**Comment by sahilkr9** [comment]
I want to work on this issue under JWOC

**Comment by Drexter-07** [comment]
Hello myself Sahil. I want to work on this issue under JWOC. I can make a navbar.

**Comment by sayan404** [comment]
Hi, Sayan here. I am interested to do work . Please assign this project to me.

**Comment by Srijita-Mandal** [comment]
Hii, I want to work on this issue under JWOC

**Comment by Wanderer-of-the-abyss** [comment]
Hey can you assign this issue to me ?

**Comment by RustamTomer** [comment]
hey can you assign this to me

**Comment by Sanghu01** [comment]
I want to contribute in this issue .

**Comment by codervivek5** [comment]
I want to work on this issue under JWOC

**Comment by whiteHatpro** [comment]
I want to work on this issue under JWOC

**Comment by sharma-02** [comment]
I want to work on this issue under JWOC.

**Comment by Rik-21** [comment]
can i work on the issue under JWOC

**Comment by dvlsatya** [comment]
I WANT TO WORK ON THIS ISSUE UNDER JWOC

**Comment by adityarathore063** [comment]
I want to work on this issue under JWOC
