### ISSUE TITLE
Add contributors list in readme.md

### ISSUE THREAD

**Issue by shibam-naskar** [shibam-naskar/IMAGE_COMPRESOR#3]
Add contributors list at the verry bottom of readme.md with their profile picture and name.

**Comment by siddkhannaa** [comment]
i can do this

**Comment by Srijita-Mandal** [comment]
Hii, I want to work on this issue under JWOC

**Comment by Shresa** [comment]
I want to work on this issue under JWOC

**Comment by Srijita-Mandal** [comment]
@shibam-naskar Please unassign me from this issue, as this is the third issue I am with.

**Comment by Sanghu01** [comment]
I want to contribute in this issue .

**Comment by aadrikasingh18** [comment]
I want to work on this issue under JWOC

**Comment by Rishti263** [comment]
I want to work on this issue under JWOC

**Comment by dvlsatya** [comment]
I WANT TO WORK ON THIS ISSUE UNDER JWOC
