### ISSUE TITLE
Create a footer .

### ISSUE THREAD

**Issue by shibam-naskar** [shibam-naskar/IMAGE_COMPRESOR#6]
create a footer . 
add 
1 - copyright
2 - mention that it is a JWOC project
3 - also add a slider button for dark and light theme changing.

**Comment by 19082002** [comment]
i want to work in this issue under JWOC

**Comment by whiteHatpro** [comment]
i want to work in this issue under JWOC

**Comment by sharma-02** [comment]
I want to work in this issue under JWOC.

**Comment by Rik-21** [comment]
Can i work on this poject under JWoc

**Comment by snehasikarwar** [comment]
can i work on this ?
